### ISSUE TITLE
Can't Install the addon

### ISSUE THREAD

**Issue by josntrm** [albertogeniola/ha-meross-local-broker#10]
Hello, 

I am trying to install the addon for local LAN Meross control of my MSS310 plugs and avoid Cloud API limitations. 
But after adding the repos to my HA system, i can't install the addon.

I get this error : 
Can't install ghcr.io/albertogeniola/aarch64-meross_local_broker:0.0.1-alpha43: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=0.0.1-alpha43&fromImage=ghcr.io%2Falbertogeniola%2Faarch64-meross_local_broker&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

I am using HA on an Odroid N2+.

Thanks

**Comment by albertogeniola** [comment]
Should be fixed. The image you were trying to pull was not yet ready and published. You should try now.
