### ISSUE TITLE
Difference Between This Add-on vs Meross LAN?

### ISSUE THREAD

**Issue by timnolte** [albertogeniola/ha-meross-local-broker#17]
I've been using the [Meross LAN](https://github.com/krahabb/meross_lan) HA add-on along with you custom pairer Android app. Recently I've having a lot of issues with my devices going unavailable. I need to find a more reliable solution and wonder what the difference is with your add-on? It seems like the one I've been using has been highlighted more but if I can't use my devices reliably I don't care which add-on is the popular choice.

**Comment by albertogeniola** [comment]
Hi @timnolte ,
the Meross LAN integration is an integration explicitly designed for running locally without the need to interact with Meross APIs. This ha-meross-local-broker, instead, is a component that enables another integration - initially designed to work only with Meross Cloud API - to work locally. 

For beginners, I'd suggest to start with the [Meross LAN](https://github.com/krahabb/meross_lan) integration as it requires less experience to work. The other option, is to use the [Meross Homeassistant component](https://github.com/albertogeniola/meross-homeassistant) together with [this addon](https://github.com/albertogeniola/ha-meross-local-broker). 

Note: this addon is still in early alpha and is updated less frequently.
