### ISSUE TITLE
Can't login using the meross integration

### ISSUE THREAD

**Issue by TheBinaryLoop** [albertogeniola/ha-meross-local-broker#2]
![image](https://user-images.githubusercontent.com/13447164/171272211-b22f0be6-af05-474c-8871-dee4785b495f.png)

**Comment by albertogeniola** [comment]
Solved with latest versions of the integration and local addon. Please update and let me know if that's now working as intended.

**Comment by albertogeniola** [comment]
I am closing this as no further info was provided. Feel free to reopen if needed.
