### ISSUE TITLE
Meross Home Assistant configured, I think?

### ISSUE THREAD

**Issue by HotelAlpha4** [albertogeniola/ha-meross-local-broker#28]
Hello Alberto

I just now donated about 20 Euro today through Paypal. Thank you for the awesome effort you have put into making Meross devices work locally with HA! Very impressive work!

I believe that I have set it up correctly, and at this stage, using the steps below, the plugs are all showing in the devices tab in HA:
1) HA is running on Pi 3B+
2) Previously installed Mosquitto broker Add-On (Unsure if the Meross addons use this?? I needed it for Zigbee2MQTT anyway)
3) Added  "Meross Local Broker Addon" to the Addon store using below URL to inject it into the store:
    http://homeassistant.local:8123/_my_redirect/supervisor_add_addon_repository?repository_url=https%3A%2F%2Fgithub.com%2Falbertogeniola%2Fha-meross-local-broker
4) Then installed and configured that addin
5) Installed the Pairer app on android device from the Android app store
6) Used that pairer app to successfully connect several MSS310 Meross plugs, and they showed up in the "Local Meross Broker"
7) I already had HACS installed
8) I added "Meross Cloud IoT" from HACS UI
9) I installed and configured "Meross Cloud IoT" using the "Add Integration" button in Devices & Services
10) At this point, my plugs showed up in the "Devices tab", and they are available in Node-Red

I have some questions if I may:
1) While researching this using Google search, I also installed "Meross LAN" by @krahbb using HACS, but I am unsure if this is needed at all given the above setup? Should I uninstall that, or was it really needed? Meross Lan is at the Github URL below https://github.com/krahabb/meross_lan
2) Initially, I set up SSL certs using the link below, but I assume this is not needed at all, and the files can be deleted?
    https://wltd.org/posts/how-to-use-meross-smart-devices-as-cheap-offline-iot
3) I am most interested in creating a Node-Red flow to sense the amps being used by a Meross plug, and turning the plug off when  the Amp draw is below a set Amperage. Do you have any Node-Red flows that do something similar that you could send me to get started with creating this flow? I am new to Node-Red and am unsure how to integrate detection and control of the Meross plugs using Node Red
4) This is less important, but when the plugs were connected to the Meross cloud, and using the Meross android app, there was a way to set a plug to turn off after x minutes whenever it is turned on. I am assuming that this was something that is not done in the Android app? It is not important if I can control it from Node-Red and HA.
5) I am happy to help out with testing, and maybe coding if that helps?

Again, huge thanks for your efforts on this.

Edit: I can confirm that I can see the on/off status of the plugs in the HA dashboard, and can turn them on/off from there. But I cannot see the Volts, amps, or watts in there, they are all 0 no matter what I have plugged in. Is this something I have to do more configuration for?

**Comment by kusannaghi** [comment]
When i try install Meross Cloud IoT this part looks that work, but no device show. Nothing happens. But in Local Meross Bloker i can pair one device. 
What do i do wrong?

**Comment by albertogeniola** [comment]
Hi @HotelAlpha4 ,

thanks for the support! I'll answer to your questions.
1. Meross LAN is a different integration and is not required when using this addon. Instead, you should be using the other addon, [Meross Homeassistant Integration](https://github.com/albertogeniola/meross-homeassistant)
2. Yes, those certificates are not needed, the addon will generate the necessary certificate on its own.
3. Sorry, I don't know much about node-red, but there are plenty of users out there who work with that great platform. You might get help from other forums
4. You are right. The "timer" functionality is not implemented at the moment. I don't think it'll be added in the short term.
5. Thanks a lot!

Regarding the Volts, Amps, Watts missing from the data, can you please post a screenshot about that?
