### ISSUE TITLE
Cannot connect to host iot.meross.com - certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by MiguelGArgiles** [albertogeniola/ha-meross-local-broker#32]
I am having an issue trying to configure my email and password using "Meross Link". It seems that the CA certificate that signs iot.meross.com is not valid (maybe is not installed).

I send the screendshot of the error and the log.

My system is fully updated with last stable versions available:
- Meross Local Broket 0.0.1-rc0
- Home Assistant 2023.1.5
- Supervisor 2022.12.1
- Operating System 9.4
- HACS: 1.29.1

Thanks for your help and congratulations for the Meross Integration with Home Assistant, is really useful.
![errorMeross](https://user-images.githubusercontent.com/15852160/213187382-1adbd1a9-8ce5-4a23-87c9-5594e49e0c7b.png)

[errorLoginMesos.txt](https://github.com/albertogeniola/ha-meross-local-broker/files/10445592/errorLoginMesos.txt)

**Comment by MatGriffin** [comment]
Same issue.

**Comment by albertogeniola** [comment]
Hi!
Should be fixed with latest version (alpha50). Sorry for being so late!
