### ISSUE TITLE
Can't update local broker addon

### ISSUE THREAD

**Issue by DeamBeam** [albertogeniola/ha-meross-local-broker#39]
Homeassistant shows the avaiable update, but when i press update, after a short while the following message pops up:

Can't install ghcr.io/albertogeniola/amd64-meross_local_broker:0.0.1-alpha46: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.0.1-alpha46&fromImage=ghcr.io%2Falbertogeniola%2Famd64-meross_local_broker&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

Tried restarting Homeassitant with no success.

**Comment by sk8er000** [comment]
Same error here:

`Invocazione del servizio update/install non riuscita. Error updating Meross Local Broker Addon: Can't install ghcr.io/albertogeniola/aarch64-meross_local_broker:0.0.1- alpha46: 500 Server Error for

http+docker://localhost/v1.43/images/create?tag=0.0.1- alpha46&fromImage=ghcr.io%2Falbertogeniola%2Faarch64- meross_local_broker&platform=linux%2Farm64: Internal Server Error ("manifest unknown")`

**Comment by albertogeniola** [comment]
Hi,

it should be fine now. Please try again and let me know if that works now.

**Comment by sk8er000** [comment]
For the moment it's updating, it's taking a while but the update started with no errors

**Comment by sk8er000** [comment]
unfortunately new orrer from the log after the succesful update:

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
fix-attrs: info: applying /etc/fix-attrs.d/50-mosquitto
s6-chown: fatal: unable to chown /etc/mosquitto/certs/server.conf
ca.conf: No such file or directory
fix-attrs: warning: fix-attrs is deprecated, please fix volume permissions in your container manager instead
fix-attrs: warning: some fix files failed to apply
s6-rc: warning: unable to start service fix-attrs: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.`

**Comment by sk8er000** [comment]
Updating from  0.0.1-alpha45 to  0.0.1-alpha47 this time was flawlessy!

Thank you

**Comment by WvanWaas** [comment]
Very Sorry but 48:
Can't install ghcr.io/albertogeniola/aarch64-meross_local_broker:0.0.1-alpha48: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.0.1-alpha48&fromImage=ghcr.io%2Falbertogeniola%2Faarch64-meross_local_broker&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

**Comment by sk8er000** [comment]
Same error here trying to update from 0.0.1-alpha47 to 0.0.1-alpha48

**Comment by albertogeniola** [comment]
Duplicate #40. Closing.
